adding files

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -5,8 +5,8 @@
 # https://github.com/vsoch/continuous-build/tree/support/singularity/.circleci
 
 # In addition to the variables defined above, you should set the GITHUB_EMAIL
-# to be the email associated with the repo (for deploy to Github pages).
-# if not set, this step won't be done 
+# and GITHUB_USER to be the email associated with the repo 
+# (for deploy to Github pages). if not set, this step won't be done 
 
 
 ################################################################################
@@ -57,6 +57,10 @@ dockerenv: &dockerenv
             CONTAINER_NAME="${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}"
         fi
         echo "Container name is ${CONTAINER_NAME}"
+        if [ ! -n "${DOCKERFILE_PATH:-}" ]; then
+            DOCKERFILE_PATH="Dockerfile";
+        fi
+        echo "Dockerfile will be looked for at ${DOCKERFILE_PATH}"
         # If not set, define REPO_NAME
         if [ ! -n "${REPO_NAME:-}" ]; then
             LOCAL_REPO="${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}"
@@ -129,40 +133,21 @@ githubsetup: &githubsetup
         fi
 
 
-repo2docker: &repo2docker
-    name: Run jupyter-repo2docker to generate Docker Container
+dockerbuild: &dockerbuild
+    name: Build Docker Container
     no_output_timeout: 60m
     command: |
-        echo "0. Installing dependencies..."
-        python3 -m venv venv
-        . venv/bin/activate
-        pip install jupyter-repo2docker
-        export VERSION=$(python3 -c "import repo2docker; print(repo2docker.__version__)")
-        echo "repo2docker version: ${VERSION}"
-        echo "1. Preparing building environment"
-        echo "Working directory is ${PWD}"
-        # If not set, define NOTEBOOK_PERMISSION
-        if [ ! -n "${NOTEBOOK_PERMISSION:-}" ]; then
-            NOTEBOOK_PERMISSION=777;
-        fi
-        # If not set, define NOTEBOOK_USERNAME
-        if [ ! -n "${NOTEBOOK_USERNAME:-}" ]; then
-            NOTEBOOK_USERNAME=joyvan;
-        fi
+        echo "0. Building Docker Container"
         source ${BASH_ENV}
-        echo "2. Running jupyter-repo2docker..."
-        echo "jupyter-repo2docker --debug --user-name ${NOTEBOOK_USERNAME} --user-id 1000 --no-run --image-name ${CONTAINER_NAME}:${DOCKER_TAG} ${REPO_NAME}"
-        jupyter-repo2docker --debug --user-name ${NOTEBOOK_USERNAME} --user-id 1000 --no-run --image-name "${CONTAINER_NAME}:${DOCKER_TAG}" "${REPO_NAME}"
-        # Issue command to make /home/${NOTEBOOK_USERNAME} read/write for any user, to support Singularity
-        echo "Changing permissions to chmod -R ${NOTEBOOK_PERMISSION} /home/${NOTEBOOK_USERNAME}"
-        docker run --name repo2docker -td "${CONTAINER_NAME}:${DOCKER_TAG}"
-        docker exec repo2docker chmod -R ${NOTEBOOK_PERMISSION} "/home/${NOTEBOOK_USERNAME}"
-        docker commit repo2docker "${CONTAINER_NAME}:${DOCKER_TAG}"
+        if [ ! -f "${DOCKERFILE_PATH}" ]; then
+            echo "Cannot find ${DOCKERFILE_PATH}, exiting build.";
+            exit 1;
+        else
+            echo "Dockerfile found at ${DOCKERFILE_PATH}";
+        fi
+        docker build --name docker-share -td "${CONTAINER_NAME}:${DOCKER_TAG}"
         docker ps
         docker images
-
-# step 1: get into functions
-# step 2: define consistent way to define variavbles for functions
 
 
 ################################################################################
@@ -193,7 +178,7 @@ jobs:
       - checkout
       - setup_remote_docker
       - run: *dockerenv
-      - run: *repo2docker
+      - run: *dockerbuild
       - run: *dockersave
       - persist_to_workspace:
           root: /tmp
